# Generated by Django 2.2.3 on 2019-07-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naynay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='naynay.Address'),
        ),
    ]
