# Generated by Django 2.2.9 on 2020-01-03 13:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('naynay', '0005_auto_20190712_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='naynay.Person'),
        ),
    ]
