# Generated by Django 2.2.9 on 2020-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naynay', '0007_auto_20200103_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(
                auto_now=True, verbose_name='date created'),
        ),
    ]
