# Generated by Django 2.2.9 on 2020-01-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naynay', '0008_blog_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTip',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True, serialize=False, to='naynay.Blog')),
                ('isWeekTip', models.BooleanField(default=True)),
            ],
            bases=('naynay.blog',),
        ),
    ]
