version: '3'

services:
  db:
    image: postgres
  django:
    build: ./api
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./api:/app/api
    ports:
      - '9000:9000'
    depends_on:
      - db
